package net.todd.biblestudy.db;

import java.util.List;

import net.todd.biblestudy.common.BiblestudyException;

public interface ILinkDao
{
	/**
	 * create a link in the database
	 * 
	 * @param link
	 * @return the id for the inserted link generated by the insert process
	 * @throws BiblestudyException
	 */
	public Link createLink(Link link) throws BiblestudyException;

	/**
	 * get all links that are associated with the note with the given name
	 * 
	 * @param containingNoteId
	 * @return List of links
	 * @throws BiblestudyException
	 */
	public List<Link> getAllLinksForNote(Integer containingNoteId) throws BiblestudyException;

	/**
	 * remove the link from the database
	 * 
	 * @param newLink
	 * @throws BiblestudyException
	 */
	public void removeLink(Link link) throws BiblestudyException;

	/**
	 * update existing link in the database
	 * 
	 * @param link
	 *            to be updated
	 * @throws BiblestudyException
	 */
	public void updateLink(Link link) throws BiblestudyException;

	/**
	 * removes all links associated with the note
	 * 
	 * @param note
	 *            whose links will be removed
	 * @throws BiblestudyException
	 */
	public void removeAllLinksForNote(Note note) throws BiblestudyException;

	/**
	 * when renaming a note, you need to update all links that link to old note
	 * name, this will return such links
	 * 
	 * @param oldNoteName
	 * @return
	 * @throws BiblestudyException
	 */
	public List<Link> getAllLinksThatLinkTo(String oldNoteName) throws BiblestudyException;
}
