package net.todd.biblestudy.db;

import java.sql.SQLException;
import java.util.List;

public interface ILinkDao
{
	/**
	 * create a link in the database
	 * 
	 * @param link
	 * @return the id for the inserted link generated by the insert process
	 * @throws SQLException
	 */
	public Link createLink(Link link) throws SQLException;
	
	/**
	 * get all links that are associated with the note with the given name
	 * 
	 * @param containingNoteId
	 * @return List of links
	 * @throws SQLException
	 */
	public List<Link> getAllLinksForNote(Integer containingNoteId) throws SQLException;
	
	/**
	 * remove the link from the database
	 * 
	 * @param newLink
	 * @throws SQLException
	 */
	public void removeLink(Link link) throws SQLException;

	/**
	 * update existing link in the database
	 * 
	 * @param link
	 * @throws SQLException
	 */
	public void updateLink(Link link) throws SQLException;
}
