ALTER TABLE NOTES ADD N_CREATED TIMESTAMP;

UPDATE NOTES SET N_CREATED = N_LAST_MODIFIED;

COMMIT;

ALTER TABLE NOTES MODIFY N_CREATED TIMESTAMP NOT NULL;
ALTER TABLE NOTES MODIFY N_NAME VARCHAR(256) NOT NULL;
