DROP TABLE IF EXISTS LINKS;
DROP TABLE IF EXISTS NOTES;

CREATE TABLE LINKS
(
	L_ID INT NOT NULL AUTO_INCREMENT,
	L_NOTE_ID INT NOT NULL,
	L_TO_NOTE_NAME VARCHAR(256),
	L_TO_REFERENCE VARCHAR(256),
	L_START INT NOT NULL,
	L_END INT NOT NULL,
	PRIMARY KEY (L_ID)
);

CREATE TABLE NOTES
(
	N_ID INT NOT NULL AUTO_INCREMENT,
	N_NAME VARCHAR(256) NOT NULL,
	N_TEXT TEXT,
	N_LAST_MODIFIED TIMESTAMP NOT NULL,
	N_CREATED TIMESTAMP NOT NULL,
	PRIMARY KEY (N_ID)
);
