
INSERT INTO VERSIONS (VERSION_ID, VERSION_TEXT) VALUES (31, 'NIV');
INSERT INTO VERSIONS (VERSION_ID, VERSION_TEXT) VALUES (49, 'NASB');
INSERT INTO VERSIONS (VERSION_ID, VERSION_TEXT) VALUES (47, 'ESV');
INSERT INTO VERSIONS (VERSION_ID, VERSION_TEXT) VALUES (72, 'TNIV');
INSERT INTO VERSIONS (VERSION_ID, VERSION_TEXT) VALUES (50, 'NKJV');

commit;
